<a href="https://colab.research.google.com/github/vladijarosz/VJaroszewski-econ/blob/main/res_netas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
!wget -O "deuda%20multilaterales.xlsx" "https://github.com/vladijarosz/VJaroszewski-econ/raw/refs/heads/main/Codigos_resNet/datos/deuda%20multilaterales.xlsx"

deuda_multi = pd.read_excel("deuda%20multilaterales.xlsx" , sheet_name="deuMult")
encajes = pd.read_excel("deuda%20multilaterales.xlsx" , sheet_name="dep y encajes")
bop_1 = pd.read_excel("deuda%20multilaterales.xlsx" , sheet_name="bopreal_1")
bop_2 = pd.read_excel("deuda%20multilaterales.xlsx" , sheet_name="bopreal_2")
bop_3 = pd.read_excel("deuda%20multilaterales.xlsx" , sheet_name="bopreal_3")
bop_4 = pd.read_excel("deuda%20multilaterales.xlsx" , sheet_name="bopreal_4")

--2026-03-03 16:03:54--  https://github.com/vladijarosz/VJaroszewski-econ/raw/refs/heads/main/Codigos_resNet/datos/deuda%20multilaterales.xlsx
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/vladijarosz/VJaroszewski-econ/refs/heads/main/Codigos_resNet/datos/deuda%20multilaterales.xlsx [following]
--2026-03-03 16:03:54--  https://raw.githubusercontent.com/vladijarosz/VJaroszewski-econ/refs/heads/main/Codigos_resNet/datos/deuda%20multilaterales.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48727 (48K) [application/octet-stream]
Saving to: ‘deuda%20multilaterales.xlsx’

deuda%20multilatera 100%[===================>]  47.58K  --.-KB/s    in 0.03s

2026-03-03 16:03:55 (1.35 MB/s) - ‘deuda%20multilaterales.xlsx’ saved [48727/48727]

In [ ]:
bop_2['fecha'] = pd.to_datetime(bop_2['fecha'])
bop_2['fecha'] = bop_2['fecha'].dt.to_period('M')

bop_1['fecha'] = pd.to_datetime(bop_1['fecha'])
bop_1['fecha'] = bop_1['fecha'].dt.to_period('M')

bop_3['fecha'] = pd.to_datetime(bop_3['fecha'])
bop_3['fecha'] = bop_3['fecha'].dt.to_period('M')

bop_4['fecha'] = pd.to_datetime(bop_4['fecha'])
bop_4['fecha'] = bop_4['fecha'].dt.to_period('M')

In [ ]:
bop = (
    bop_1
    .merge(bop_2, on='fecha', how='outer')
    .merge(bop_3, on='fecha', how='outer')
    .merge(bop_4, on='fecha', how='outer')
)

In [ ]:
import pandas as pd

# Asegurar que fecha sea Period mensual
bop['fecha'] = pd.PeriodIndex(bop['fecha'], freq='M')

# Poner fecha como índice
bop = bop.set_index('fecha')

# Crear rango completo mensual
rango_completo = pd.period_range(
    start=bop.index.min(),
    end=bop.index.max(),
    freq='M'
)

# Reindexar (esto agrega los meses faltantes con NaN)
bop = bop.reindex(rango_completo)

# Opcional: volver a tener fecha como columna
bop = bop.reset_index().rename(columns={'index': 'fecha'})
bop

      fecha  bopreal_1       FFj_x   FFj_y    FFj
0   2024-01        0.0         NaN     0.0    NaN
1   2024-02        NaN    0.000000     NaN    NaN
2   2024-03        NaN         NaN     NaN    NaN
3   2024-04        NaN         NaN     NaN    NaN
4   2024-05        NaN         NaN     NaN    NaN
5   2024-06        NaN         NaN     NaN    NaN
6   2024-07        NaN  166.666667     NaN    NaN
7   2024-08        NaN  166.666667   150.0    NaN
8   2024-09        NaN  166.666667     NaN    NaN
9   2024-10      250.0  166.666667     NaN    NaN
10  2024-11        NaN  166.666667   150.0    NaN
11  2024-12        NaN  166.666667     NaN    NaN
12  2025-01        NaN  166.666667     NaN    NaN
13  2025-02        NaN  166.666667   150.0    NaN
14  2025-03      250.0  166.666667     NaN    NaN
15  2025-04        NaN  166.666667     NaN    NaN
16  2025-05        NaN  166.666667   150.0    NaN
17  2025-06        NaN  166.666667     NaN   13.5
18  2025-07        NaN         NaN     NaN    NaN
19  2025-08        NaN         NaN   150.0    NaN
20  2025-09      250.0         NaN     NaN    NaN
21  2025-10        NaN         NaN     NaN   13.5
22  2025-11        NaN         NaN  1150.0    NaN
23  2025-12        NaN         NaN     NaN    NaN
24  2026-01        NaN         NaN     NaN    NaN
25  2026-02        NaN         NaN  1100.0    NaN
26  2026-03      250.0         NaN     NaN    NaN
27  2026-04        NaN         NaN     NaN   13.5
28  2026-05        NaN         NaN  1050.0    NaN
29  2026-06        NaN         NaN     NaN    NaN
30  2026-07        NaN         NaN     NaN    NaN
31  2026-08        NaN         NaN     NaN    NaN
32  2026-09      250.0         NaN     NaN    NaN
33  2026-10        NaN         NaN     NaN   13.5
34  2026-11        NaN         NaN     NaN    NaN
35  2026-12        NaN         NaN     NaN    NaN
36  2027-01        NaN         NaN     NaN    NaN
37  2027-02        NaN         NaN     NaN    NaN
38  2027-03      250.0         NaN     NaN    NaN
39  2027-04     2750.0         NaN     NaN   13.5
40  2027-05        NaN         NaN     NaN    NaN
41  2027-06        NaN         NaN     NaN    NaN
42  2027-07        NaN         NaN     NaN    NaN
43  2027-08        NaN         NaN     NaN    NaN
44  2027-09      125.0         NaN     NaN    NaN
45  2027-10     2625.0         NaN     NaN   13.5
46  2027-11        NaN         NaN     NaN    NaN
47  2027-12        NaN         NaN     NaN    NaN
48  2028-01        NaN         NaN     NaN    NaN
49  2028-02        NaN         NaN     NaN    NaN
50  2028-03        NaN         NaN     NaN    NaN
51  2028-04        NaN         NaN     NaN   13.5
52  2028-05        NaN         NaN     NaN    NaN
53  2028-06        NaN         NaN     NaN    NaN
54  2028-07        NaN         NaN     NaN    NaN
55  2028-08        NaN         NaN     NaN    NaN
56  2028-09        NaN         NaN     NaN    NaN
57  2028-10        NaN         NaN     NaN  913.5

In [ ]:
bop = bop.set_index('fecha')
bop['Bopreal'] = bop.sum(axis=1)
bop['bop_año'] = (
    bop['Bopreal'][::-1]
    .rolling(12)
    .sum()[::-1]
)
bop

         bopreal_1       FFj_x   FFj_y    FFj      Bopreal      bop_año
fecha
2024-01        0.0         NaN     0.0    NaN     0.000000  1550.000000
2024-02        NaN    0.000000     NaN    NaN     0.000000  1716.666667
2024-03        NaN         NaN     NaN    NaN     0.000000  2033.333333
2024-04        NaN         NaN     NaN    NaN     0.000000  2450.000000
2024-05        NaN         NaN     NaN    NaN     0.000000  2616.666667
2024-06        NaN         NaN     NaN    NaN     0.000000  2933.333333
2024-07        NaN  166.666667     NaN    NaN   166.666667  3113.500000
2024-08        NaN  166.666667   150.0    NaN   316.666667  2946.833333
2024-09        NaN  166.666667     NaN    NaN   166.666667  2780.166667
2024-10      250.0  166.666667     NaN    NaN   416.666667  2863.500000
2024-11        NaN  166.666667   150.0    NaN   316.666667  2460.333333
2024-12        NaN  166.666667     NaN    NaN   166.666667  3293.666667
2025-01        NaN  166.666667     NaN    NaN   166.666667  3127.000000
2025-02        NaN  166.666667   150.0    NaN   316.666667  2960.333333
2025-03      250.0  166.666667     NaN    NaN   416.666667  3743.666667
2025-04        NaN  166.666667     NaN    NaN   166.666667  3577.000000
2025-05        NaN  166.666667   150.0    NaN   316.666667  3423.833333
2025-06        NaN  166.666667     NaN   13.5   180.166667  4157.166667
2025-07        NaN         NaN     NaN    NaN     0.000000  3977.000000
2025-08        NaN         NaN   150.0    NaN   150.000000  3977.000000
2025-09      250.0         NaN     NaN    NaN   250.000000  3827.000000
2025-10        NaN         NaN     NaN   13.5    13.500000  3827.000000
2025-11        NaN         NaN  1150.0    NaN  1150.000000  3827.000000
2025-12        NaN         NaN     NaN    NaN     0.000000  2677.000000
2026-01        NaN         NaN     NaN    NaN     0.000000  2677.000000
2026-02        NaN         NaN  1100.0    NaN  1100.000000  2677.000000
2026-03      250.0         NaN     NaN    NaN   250.000000  1577.000000
2026-04        NaN         NaN     NaN   13.5    13.500000  1577.000000
2026-05        NaN         NaN  1050.0    NaN  1050.000000  4327.000000
2026-06        NaN         NaN     NaN    NaN     0.000000  3277.000000
2026-07        NaN         NaN     NaN    NaN     0.000000  3277.000000
2026-08        NaN         NaN     NaN    NaN     0.000000  3277.000000
2026-09      250.0         NaN     NaN    NaN   250.000000  3277.000000
2026-10        NaN         NaN     NaN   13.5    13.500000  3152.000000
2026-11        NaN         NaN     NaN    NaN     0.000000  5777.000000
2026-12        NaN         NaN     NaN    NaN     0.000000  5777.000000
2027-01        NaN         NaN     NaN    NaN     0.000000  5777.000000
2027-02        NaN         NaN     NaN    NaN     0.000000  5777.000000
2027-03      250.0         NaN     NaN    NaN   250.000000  5777.000000
2027-04     2750.0         NaN     NaN   13.5  2763.500000  5527.000000
2027-05        NaN         NaN     NaN    NaN     0.000000  2777.000000
2027-06        NaN         NaN     NaN    NaN     0.000000  2777.000000
2027-07        NaN         NaN     NaN    NaN     0.000000  2777.000000
2027-08        NaN         NaN     NaN    NaN     0.000000  2777.000000
2027-09      125.0         NaN     NaN    NaN   125.000000  2777.000000
2027-10     2625.0         NaN     NaN   13.5  2638.500000  2652.000000
2027-11        NaN         NaN     NaN    NaN     0.000000   927.000000
2027-12        NaN         NaN     NaN    NaN     0.000000          NaN
2028-01        NaN         NaN     NaN    NaN     0.000000          NaN
2028-02        NaN         NaN     NaN    NaN     0.000000          NaN
2028-03        NaN         NaN     NaN    NaN     0.000000          NaN
2028-04        NaN         NaN     NaN   13.5    13.500000          NaN
2028-05        NaN         NaN     NaN    NaN     0.000000          NaN
2028-06        NaN         NaN     NaN    NaN     0.000000          NaN
2028-07        NaN         NaN     NaN    NaN     0.000000          NaN
2028-08        NaN         NaN     NaN    NaN     0.000000          NaN
2028-09        NaN         NaN     NaN    NaN     0.000000          NaN
2028-10        NaN         NaN     NaN  913.5   913.500000          NaN

In [ ]:
deuda_multi.index=deuda_multi['fecha']
deuda_multi['suma un año']= (
    deuda_multi["vencimiento"][::-1]
    .rolling("365D")
    .sum()[::-1]
)/1000

In [ ]:
deuda_multi = deuda_multi.drop(columns=['fecha','vencimiento'])
deuda_multi=deuda_multi.rename(columns={'suma un año':'deuda_mult'})

In [ ]:
encajes.index=encajes['fecha']
encajes=encajes.drop(columns=['fecha'])
encajes['dep_Nac_ext']=encajes['dep_Nac_ext']/1000
encajes['encajes_ext']=encajes['encajes_ext']/1000

In [ ]:
deuda_multi

             deuda_mult
fecha
2020-01-01  4192.466962
2020-02-01  4186.475316
2020-03-01  4108.444651
2020-04-01  4074.359194
2020-05-01  4055.867008
...                 ...
2026-05-01  4138.873918
2026-06-01  2922.659515
2026-07-01  2671.735586
2026-08-01  2426.848639
2026-09-01  1448.390607

[81 rows x 1 columns]

In [ ]:
df=deuda_multi.merge(encajes['dep_Nac_ext'], left_index=True, right_index=True, how="left")

df

             deuda_mult  dep_Nac_ext
fecha
2020-01-01  4192.466962    76.596291
2020-02-01  4186.475316    61.961563
2020-03-01  4108.444651    92.408099
2020-04-01  4074.359194   117.816430
2020-05-01  4055.867008    68.050623
...                 ...          ...
2026-05-01  4138.873918          NaN
2026-06-01  2922.659515          NaN
2026-07-01  2671.735586          NaN
2026-08-01  2426.848639          NaN
2026-09-01  1448.390607          NaN

[81 rows x 2 columns]

In [ ]:
df_1=df.merge(encajes['encajes_ext'], left_index=True, right_index=True, how="left")


df_1=df_1['2020-01-01':'2026-01-01']
df_1.index = pd.to_datetime(df_1.index)
df_1.index = df_1.index.to_period('M')
df_1

          deuda_mult  dep_Nac_ext   encajes_ext
fecha
2020-01  4192.466962    76.596291   9958.753033
2020-02  4186.475316    61.961563  10626.529369
2020-03  4108.444651    92.408099  10314.735744
2020-04  4074.359194   117.816430  10868.490581
2020-05  4055.867008    68.050623  11220.614343
...              ...          ...           ...
2025-09  7509.516074  2327.401341  12781.037547
2025-10  8268.271439    91.943698  14048.863256
2025-11  7896.105848   212.550877  15985.266290
2025-12  6668.060111  1969.859517  15066.040280
2026-01  6413.840405   526.243735  17268.273999

[73 rows x 3 columns]

In [ ]:
df_1=df_1.merge(bop['bop_año'], left_index=True, right_index=True, how="left")
df_1

          deuda_mult  dep_Nac_ext   encajes_ext  bop_año
fecha
2020-01  4192.466962    76.596291   9958.753033      NaN
2020-02  4186.475316    61.961563  10626.529369      NaN
2020-03  4108.444651    92.408099  10314.735744      NaN
2020-04  4074.359194   117.816430  10868.490581      NaN
2020-05  4055.867008    68.050623  11220.614343      NaN
...              ...          ...           ...      ...
2025-09  7509.516074  2327.401341  12781.037547   3827.0
2025-10  8268.271439    91.943698  14048.863256   3827.0
2025-11  7896.105848   212.550877  15985.266290   3827.0
2025-12  6668.060111  1969.859517  15066.040280   2677.0
2026-01  6413.840405   526.243735  17268.273999   2677.0

[73 rows x 4 columns]